# Generated by Django 6.0.2 on 2026-03-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_church_id_alter_churchuser_id_alter_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
