# Generated by Django 6.0.2 on 2026-03-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notification_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="approved",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
