# Generated by Django 6.0.2 on 2026-03-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_prayerrequest_approved_prayerrequest_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayerrequest",
            name="name",
        ),
    ]
