# Generated by Django 5.2.12 on 2026-03-30 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_church_id_alter_churchuser_id_alter_event_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Announcment",
            new_name="Announcement",
        ),
    ]
