# Generated by Django 6.0.2 on 2026-04-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_announcement_id_alter_chatmessage_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="last_edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
